#!/bin/bash

err="ERROR: OpenArena(https://aur.archlinux.org/openarena.git) not  installed!"

# This is needed because there are different openarena packages
if [ -d "/opt/openarena" ]; then
	FS_BASEPATH="/opt/openarena"
	/opt/openarena/omega${1}-x64 +set fs_basepath "${FS_BASEPATH}"
else
	echo "${err}"
	exit 1
fi
